import React from 'react';
import './ExamDisplay.css';
import * as XLSX from 'xlsx';

const ExamDisplay = ({ examData, onGenerateNew }) => {
  const { topic, questionCount, questions, generatedAt } = examData;

  const handlePrint = () => {
    window.print();
  };

  const handleDownload = () => {
    const examContent = `
${topic.toUpperCase()} EXAM
Generated on: ${new Date(generatedAt).toLocaleDateString()}
Number of Questions: ${questionCount}

${questions.map((q, index) => `${index + 1}. ${q.question}\n\nAnswer: _______________\n\n`).join('')}

---
Generated by AI Exam Generator
    `.trim();

    const blob = new Blob([examContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${topic.toLowerCase().replace(/\s+/g, '-')}-exam.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // NEW FUNCTION: Excel Download Handler
  const handleExcelDownload = () => {
    // Create exam data for Excel
    const examInfo = [
      ['AI Exam Generator - ' + topic.toUpperCase() + ' EXAM'],
      [''],
      ['Generated on:', formatDate(generatedAt)],
      ['Number of Questions:', questionCount],
      ['Subject:', topic],
      [''],
      ['STUDENT INFORMATION:'],
      ['Name:', '________________________'],
      ['Class:', '________________________'],
      ['Date:', '________________________'],
      ['Time Allowed:', '_______ minutes'],
      [''],
      ['INSTRUCTIONS:'],
      ['• Read each question carefully'],
      ['• Show your work where applicable'],
      ['• Write your answers clearly'],
      ['• Check your answers when finished'],
      [''],
      ['QUESTIONS:']
    ];

    // Add questions and answer spaces
    questions.forEach((question, index) => {
      examInfo.push([`${index + 1}.`, question.question]);
      examInfo.push(['Answer:', '']);
      examInfo.push(['']);
    });

    // Add footer
    examInfo.push(['']);
    examInfo.push(['---Generated by AI Exam Generator---']);
    examInfo.push(['© 2025 - Created for Educational Use']);

    // Create workbook and worksheet
    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(examInfo);

    // Set column widths
    const colWidths = [
      { wch: 15 }, // Column A
      { wch: 80 }  // Column B
    ];
    ws['!cols'] = colWidths;

    // Style the header
    if (ws['A1']) {
      ws['A1'].s = {
        font: { bold: true, sz: 16 },
        alignment: { horizontal: 'center' }
      };
    }

    // Add worksheet to workbook
    XLSX.utils.book_append_sheet(wb, ws, topic + ' Exam');

    // Create filename
    const filename = `${topic.toLowerCase().replace(/\s+/g, '-')}-exam.xlsx`;
    
    // Download the file
    XLSX.writeFile(wb, filename);
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  return (
    <div className="exam-display">
      <div className="exam-header no-print">
        <div className="exam-info">
          <div className="exam-icon">
            <i className="fas fa-file-text"></i>
          </div>
          <div className="exam-details">
            <h2>{topic} Exam</h2>
            <div className="exam-meta">
              <span className="meta-item">
                <i className="fas fa-list-ol"></i>
                {questionCount} Questions
              </span>
              <span className="meta-item">
                <i className="fas fa-calendar-alt"></i>
                {formatDate(generatedAt)}
              </span>
            </div>
          </div>
        </div>

        <div className="exam-actions">
          <button onClick={handlePrint} className="action-btn print-btn">
            <i className="fas fa-print"></i>
            Print Exam
          </button>
          <button onClick={handleDownload} className="action-btn download-btn">
            <i className="fas fa-download"></i>
            Download TXT
          </button>
          {/* NEW BUTTON: Excel Download */}
          <button onClick={handleExcelDownload} className="action-btn excel-btn">
            <i className="fas fa-file-excel"></i>
            Download Excel
          </button>
          <button onClick={onGenerateNew} className="action-btn new-exam-btn">
            <i className="fas fa-plus"></i>
            Generate New Exam
          </button>
        </div>
      </div>

      <div className="exam-paper">
        <div className="paper-header">
          <h1 className="exam-title">{topic} Exam</h1>
          <div className="exam-info-print">
            <div className="info-row">
              <span>Name: ________________________</span>
              <span>Date: {formatDate(generatedAt)}</span>
            </div>
            <div className="info-row">
              <span>Class: ________________________</span>
              <span>Time: _______ minutes</span>
            </div>
          </div>
          <div className="instructions">
            <h3>Instructions:</h3>
            <ul>
              <li>Read each question carefully</li>
              <li>Show your work where applicable</li>
              <li>Write your answers clearly</li>
              <li>Check your answers when finished</li>
            </ul>
          </div>
        </div>

        <div className="questions-section">
  <h3>Questions ({questionCount} questions)</h3>
  {questions.map((question, index) => {
    const qText = question.question;

    // Detect MCQ pattern → options start with "a)" or "A)"
    const mcqOptions = qText.match(/([a-d]\)|[A-D]\)).*/g);

    return (
      <div key={question.id} className="question-item">
        <div className="question-number">{index + 1}.</div>
        <div className="question-content">
          {mcqOptions ? (
            <>
              {/* Question text before options */}
              <p className="question-text">
                {qText.split(/a\)|A\)/)[0].trim()}
              </p>
              <ul className="mcq-options">
                {mcqOptions.map((opt, i) => (
                  <li key={i}>{opt.trim()}</li>
                ))}
              </ul>
            </>
          ) : (
            <>
              {/* Non-MCQ → show normal with answer line */}
              <p className="question-text">{qText}</p>
              <div className="answer-space">
                <span className="answer-label">Answer: </span>
                <div className="answer-line"></div>
              </div>
            </>
          )}
        </div>
      </div>
    );
  })}
</div>


        <div className="exam-footer">
          <div className="footer-content">
            <p>Generated by AI Exam Generator</p>
            <p>© <span id="year"></span> - Created for Educational Use</p>

            <script>
              document.getElementById("year").textContent = new Date().getFullYear();
            </script>

          </div>
        </div>
      </div>
    </div>
  );
};

export default ExamDisplay;